=== RNABioInfo/rna-interaction-format/rna-interaction-schema_v1.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://raw.githubusercontent.com/RNABioInfo/rna-interaction-specification/rna-interaction-schema_v1.json",
	"title": "RNA-RNA/Protein Interaction Format",
	"description": "The RNA Interaction Format (RIF) is focused on capturing RNA interactions in a convenient to use format.",
	"type": "array",
	"minItems": 1,
	"uniqueItems": true,
	"items": {
		"type": "object",
		"properties": {
			"ID": {
				"type": "string",
				"description": "The unique identifier for an interaction",
                "pattern": "^[0-9a-zA-z-_]*$"
			},
            "version": {
                "type": "string",
                "description": "The file version of RIF. Currently only RIFv1.0 allowed",
                "pattern": "^RIFv1.0$"
            },
			"class": {
				"enum": ["RNA-RNA", "RNA-Protein", "RNA-RNA-Protein"],
                "description": "The class of the described interaction"
			},
			"type": {
				"type": "string",
                "description": "The type of interaction, i.e. molecular mechanism"
			},
			"evidence": {
				"type": "array",
				"description": "Evidence that supports the interaction",
				"minItems": 1,
				"uniqueItems": true,
				"items": {
					"type": "object",
					"properties": {
						"type": {
							"description": "Type of evidence (e.g., prediction, experimental)",
							"type": "string"
						},
						"method": {
							"description": "Tools or laboratory techniques used",
							"type": "string"
						},
						"command": {
							"description": "Command of the computational method",
							"type": "string"
						},
						"data": {
                            "description": "Data that supports the interaction",
                            "type": "object",
                            "additionalProperties": {
                                "oneOf": [
                                    {
                                        "type": "object",
                                        "additionalProperties": {
                                            "not": { "type": "object" }
                                        }
                                    },
                                    {
                                        "not": { "type": "object" }
                                    }
                                ]
                            }
						}
					},
                    "additionalProperties": false,
					"required": ["type", "method", "data"]
				}
			},
			"partners": {
				"type": "array",
                "description": "RNA/Proteins involved in the interaction",
				"items": {
					"type": "object",
					"properties": {
						"name": {
							"description": "Description of the RNA/Protein",
							"type": "string"
						},
						"symbol": {
							"description": "Scientific naming of the RNA/protein",
							"type": "string"
						},
						"type": {
							"description": "Type of the of the RNA/Protein. Should match entry in sequence ontology",
							"type": "string"
						},
						"sequence_type": {
							"description": "Type of sequence which can be either DNA, RNA or Protein",
							"enum": ["dna","rna","protein"]
						},
						"genomic_coordinates": {
							"description": "chromosome, strand and genomic coordinates of the RNA/Protein",
							"type": "string",
                            "pattern": "[a-zA-Z0-9]+:[+-]:[0-9]+-[0-9]+"
						},
						"organism_name": {
							"description": "Name of the organism",
							"type": "string"
						},
                        "organism_acc": {
							"description": "Unique accession id of the organism",
							"type": "string"
                        },
						"local_sites": {
                            "description": "Interaction sites of the organism",
							"type": "object",
                            "patternProperties": {
								"^.*$": {
                                    "type": "array",
                                    "items": {
                                        "type": "array",
                                        "minItems": 2,
                                        "maxItems": 2,
                                        "items": {
                                            "type": "number"
                                        }
                                    }
                                }
                            }
						},
						"info": {
							"type": "object",
                            "properties": {
                                "description": {
                                    "type": "string",
                                    "description": "Summary of the "
                                },
                                "sequence": {
                                    "type": "string",
                                    "description": "The sequence of the RNA/Protein",
                                    "pattern": "^([ATGC]*|[ARNDCQEGHILKMFPSTWYV]*)$"
                                },
                                "structure": {
                                    "type": "string",
                                    "description": "The structure of the RNA in dot-bracket notation",
                                    "pattern": "^[.()]*$"
                                },
                                "note": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties":true
						},
						"custom": {
							"type": "object"
						}
					},
                    "additionalProperties": false,
					"required": ["name", "type", "local_sites"]
				}
			}
		},
        "additionalProperties": false,
		"required": ["ID", "version", "class", "type", "evidence", "partners"]
	}
}

=== RNABioInfo/rna-interaction-format/examples/AGO2_mir29_CLIP.json
[
  {
    "ID": "1",
    "version": "RIFv1.0",
    "class": "RNA-Protein",
    "type": "RNA binding",
    "evidence": [
      {
        "type": "experimental",
        "method": "CLIP",
        "data": {
          "timepoint": {
            "h_post_injury": 3
          }
        }
      }
    ],
    "partners": [
      {
        "name": "Family with sequence similarity 168 member B",
        "symbol": "Fam168b",
        "type": "mRNA",
        "genomic_coordinates": "chr1:-:34813219-34843065",
        "organism_name": "Mus musculus",
        "organism_acc": "GRCm38.p6",
        "local_sites": {
          "AGO": [
            [
              2020,
              2100
            ]
          ],
          "mir29": [
            [
              2050,
              2070
            ]
          ]
        },
        "custom": {
        }
      },
      {
        "name": "Histone deacetylase 4",
        "symbol": "Hdac4",
        "type": "mRNA",
        "genomic_coordinates": "chr1:-:91928779-92195699",
        "organism_name": "Mus musculus",
        "organism_acc": "GRCm38.p6",
        "local_sites": {
          "AGO": [
            [
              3936,
              4016
            ],
            [
              4026,
              4106
            ]
          ],
          "mir29": [
            [
              3976,
              3996
            ],
            [
              4056,
              4076
            ]
          ]
        },
        "custom": {
        }
      },
      {
        "name": "RNA binding protein fox-1 homolog",
        "symbol": "Rbfox2",
        "type": "mRNA",
        "genomic_coordinates": "chr15:-:77078990-77307004",
        "organism_name": "Mus musculus",
        "organism_acc": "GRCm38.p6",
        "local_sites": {
          "AGO": [
            [
              4652,
              4732
            ],
            [
              4784,
              4864
            ]
          ],
          "mir29": [
            [
              4682,
              4712
            ],
            [
              4685,
              4705
            ]
          ]
        },
        "custom": {
        }
      },
      {
        "name": "argonaute RISC catalytic subunit 2",
        "symbol": "AGO2",
        "type": "Protein",
        "genomic_coordinates": "chr15:-:73095844-73184935",
        "organism_name": "Mus musculus",
        "organism_acc": "GRCm38.p6",
        "local_sites": {
          "mir29": [
            [
              678,
              1041
            ]
          ],
          "Fam168b": [
            [
              1719,
              2580
            ]
          ],
          "Hdac4": [
            [
              1719,
              2580
            ]
          ],
          "Rbfox2": [
            [
              1719,
              2580
            ]
          ]
        },
        "custom": {
        }
      }
    ]
  },
  {
    "ID": "2",
    "version": "RIFv1.0",
    "class": "RNA-RNA",
    "type": "RNA binding",
    "evidence": [
      {
        "type": "experimental",
        "method": "CLIP",
        "data": {
          "timepoint": {
            "h_post_injury": 3
          }
        }
      }
    ],
    "partners": [
      {
        "name": "Family with sequence similarity 168 member B",
        "symbol": "Fam168b",
        "type": "mRNA",
        "genomic_coordinates": "chr1:-:34813219-34843065",
        "organism_name": "Mus musculus",
        "organism_acc": "GRCm38.p6",
        "local_sites": {
          "AGO": [
            [
              2020,
              2100
            ]
          ],
          "mir29": [
            [
              2050,
              2070
            ]
          ]
        },
        "custom": {
        }
      },
      {
        "name": "Histone deacetylase 4",
        "symbol": "Hdac4",
        "type": "mRNA",
        "genomic_coordinates": "chr1:-:91928779-92195699",
        "organism_name": "Mus musculus",
        "organism_acc": "GRCm38.p6",
        "local_sites": {
          "AGO": [
            [
              3936,
              4016
            ],
            [
              4026,
              4106
            ]
          ],
          "mir29": [
            [
              3976,
              3996
            ],
            [
              4056,
              4076
            ]
          ]
        },
        "custom": {
        }
      },
      {
        "name": "RNA binding protein fox-1 homolog",
        "symbol": "Rbfox2",
        "type": "mRNA",
        "genomic_coordinates": "chr15:-:77078990-77307004",
        "organism_name": "Mus musculus",
        "organism_acc": "GRCm38.p6",
        "local_sites": {
          "AGO": [
            [
              4652,
              4732
            ],
            [
              4784,
              4864
            ]
          ],
          "mir29": [
            [
              4682,
              4712
            ],
            [
              4685,
              4705
            ]
          ]
        },
        "custom": {
        }
      },
      {
        "name": "microRNA 29",
        "symbol": "mir29",
        "type": "miRNA",
        "genomic_coordinates": "chr6:-:31062660-31062747",
        "organism_name": "Mus musculus",
        "organism_acc": "GRCm38.p6",
        "local_sites": {
          "AGO": [
            [
              16,
              37
            ]
          ],
          "Fam168b": [
            [
              17,
              25
            ]
          ],
          "Hdac4": [
            [
              17,
              25
            ]
          ],
          "Rbfox2": [
            [
              17,
              25
            ]
          ]
        },
        "custom": {
        }
      }
    ]
  },
  {
    "ID": "3",
    "version": "RIFv1.0",
    "class": "RNA-RNA-Protein",
    "type": "RNA binding",
    "evidence": [
      {
        "type": "experimental",
        "method": "CLIP",
        "data": {
          "timepoint": {
            "h_post_injury": 3
          }
        }
      }
    ],
    "partners": [
      {
        "name": "Family with sequence similarity 168 member B",
        "symbol": "Fam168b",
        "type": "mRNA",
        "genomic_coordinates": "chr1:-:34813219-34843065",
        "organism_name": "Mus musculus",
        "local_sites": {
          "AGO": [
            [
              2020,
              2100
            ]
          ],
          "mir29": [
            [
              2050,
              2070
            ]
          ]
        },
        "custom": {
          "organism_acc": "GRCm38.p6"
        }
      },
      {
        "name": "Histone deacetylase 4",
        "symbol": "Hdac4",
        "type": "mRNA",
        "genomic_coordinates": "chr1:-:91928779-92195699",
        "organism_name": "Mus musculus",
        "organism_acc": "GRCm38.p6",
        "local_sites": {
          "AGO": [
            [
              3936,
              4016
            ],
            [
              4026,
              4106
            ]
          ],
          "mir29": [
            [
              3976,
              3996
            ],
            [
              4056,
              4076
            ]
          ]
        },
        "custom": {
        }
      },
      {
        "name": "RNA binding protein fox-1 homolog",
        "symbol": "Rbfox2",
        "type": "mRNA",
        "genomic_coordinates": "chr15:-:77078990-77307004",
        "organism_name": "Mus musculus",
        "organism_acc": "GRCm38.p6",
        "local_sites": {
          "AGO": [
            [
              4652,
              4732
            ],
            [
              4784,
              4864
            ]
          ],
          "mir29": [
            [
              4682,
              4712
            ],
            [
              4685,
              4705
            ]
          ]
        },
        "custom": {
        }
      },
      {
        "name": "microRNA 29",
        "symbol": "mir29",
        "type": "miRNA",
        "genomic_coordinates": "chr6:-:31062660-31062747",
        "organism_name": "Mus musculus",
        "organism_acc": "GRCm38.p6",
        "local_sites": {
          "AGO": [
            [
              16,
              37
            ]
          ],
          "Fam168b": [
            [
              17,
              25
            ]
          ],
          "Hdac4": [
            [
              17,
              25
            ]
          ],
          "Rbfox2": [
            [
              17,
              25
            ]
          ]
        },
        "custom": {
        }
      },
      {
        "name": "argonaute RISC catalytic subunit 2",
        "symbol": "AGO2",
        "type": "Protein",
        "genomic_coordinates": "chr15:-:73095844-73184935",
        "organism_name": "Mus musculus",
        "organism_acc": "GRCm38.p6",
        "local_sites": {
          "mir29": [
            [
              678,
              1041
            ]
          ],
          "Fam168b": [
            [
              1719,
              2580
            ]
          ],
          "Hdac4": [
            [
              1719,
              2580
            ]
          ],
          "Rbfox2": [
            [
              1719,
              2580
            ]
          ]
        },
        "custom": {
        }
      }
    ]
  }
]

=== RNABioInfo/rna-interaction-format/impl/python/RIF/tests/test.json
[{
    "ID": "1",
    "version": "RIFv1.0",
    "class": "RNA-RNA-Protein",
    "type": "basepairing",

    "evidence": [
        {
            "type": "experimental",
            "method": "gel shift assay",
            "data": {
                "URI": "https://journals.asm.org/doi/full/10.1128/JB.183.6.1997-2005.2001",
                "note": "Hfq and DsrA interact in vivo"
            }
        },
        {
            "type": "experimental",
            "method": "protein binding assay",
            "data": {
                "URI": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1370368/"
            }
        }
    ],

    "partners": [
        {
            "name": "Hfq",
            "symbol": "Hfq",
            "type": "polypeptide",
            "sequence_type": "protein",
            "genomic_coordinates": "NC_000913.3:+:4400288-4400596",
            "organism_name": "Escherichia coli K-12 MG1655",
            "organism_acc": "NC_000913.3",
            "local_sites": {
                "dsrA": [[60,78],[45,55]],
                "rpoS": [[10,40]]
            },
            "info": {
                "description": "RNA chaperone that binds small regulatory RNA (sRNAs) and mRNAs to facilitate mRNA translational regulation in response to envelope stress, environmental stress and changes in metabolite concentrations.",
                "sequence": "MAKGQSLQDPFLNALRRERVPVSIYLVNGIKLQGQIESFDQFVILLKNTVSQMVYKHAISTVVPSRPVSHHSNNAGGGTSSNYHHGSSAQNTSAQQDSEETE",
                "note": "https://www.ebi.ac.uk/pdbe/entry/pdb/5I21"
            }
        },
        {
            "name": "dsrA",
            "symbol": "dsrA",
            "type": "small_regulatory_ncRNA",
            "sequence_type": "rna",
            "genomic_coordinates": "NC_000913.3:-:2025223-2025313",
            "organism_name": "Escherichia coli K-12 MG1655",
            "organism_acc": "NC_000913.3",
            "local_sites": {
                "Hfq": [[12,30],[80,90]],
                "rpoS": [[50,70]]
            },
            "info": {
                "description": "DsrA small regulatory RNA; riboregulator of RpoS and H-NS production",
                "sequence": "AACGCATCGGATTTCCCGGTGTAACGAATTTTCAAGTGCTTCTTGCATTAGCAAGTTTGATCCCGACTCCTGCGAGTCGGGATTT",
                "structure": "...(((((((.....)))))))..(((((((...(((((.....)))))...)))))))((((((((((....)))))))))).."
            },

            "custom": {}
        },
        {
            "name": "rpoS",
            "symbol": "rpoS",
            "type": "mRNA",
            "sequence_type": "rna",
            "genomic_coordinates": "NC_000913.3:-:2866559-2867551",
            "organism_name": "Escherichia coli K-12 MG1655",
            "organism_acc": "NC_000913.3",
            "local_sites": {
                "Hfq": [[200,230]],
                "dsrA": [[587,607]]
            },
            "info": {
                "description": "RNA polymerase, sigma S (sigma 38) factor",
                "sequence": "TGAGTCAGAATACGCTGAAAGTTCATGATTTAAATGAAGATGCGGAATTTGATGAGAACGGAGTTGAGGTTTTTGACGAAAAGGCCTTAGTAGAACAGGAACCCAGTGATAACGATTTGGCCGAAGAGGAACTGTTATCGCAGGGAGCCACACAGCGTGTGTTGGACGCGACTCAGCTTTACCTTGGTGAGATTGGTTATTCACCACTGTTAACGGCCGAAGAAGAAGTTTATTTTGCGCGTCGCGCACTGCGTGGAGATGTCGCCTCTCGCCGCCGGATGATCGAGAGTAACTTGCGTCTGGTGGTAAAAATTGCCCGCCGTTATGGCAATCGTGGTCTGGCGTTGCTGGACCTTATCGAAGAGGGCAACCTGGGGCTGATCCGCGCGGTAGAGAAGTTTGACCCGGAACGTGGTTTCCGCTTCTCAACATACGCAACCTGGTGGATTCGCCAGACGATTGAACGGGCGATTATGAACCAAACCCGTACTATTCGTTTGCCGATTCACATCGTAAAGGAGCTGAACGTTTACCTGCGAACCGCACGTGAGTTGTCCCATAAGCTGGACCATGAACCAAGTGCGGAAGAGATCGCAGAGCAACTGGATAAGCCAGTTGATGACGTCAGCCGTATGCTTCGTCTTAACGAGCGCATACCTCGGTAGACACCCCGCTGGGTGGTGATTCCGAAAAAGCGTTGCTGGACATCCTGGCCGATGAAAAAGAGAACGGTCCGGAAGATACCACGCAAGATGACGATATGAAGCAGAGCATCGTCAAATGGCTGTTCGAGCTGAACGCCAAACAGCGTGAAGTGCTGGCACGTCGATTCGGTTTGCTGGGGTACGAAGCGGCAACACTGGAAGATGTAGGTCGTGAAATTGGCCTCACCCGTGAACGTGTTCGCCAGATTCAGGTTGAAGGCCTGCGCCGTTTGCGCGAAATCCTGCAAACGCAGGGGCTGAATATCGAAGCGCTGTTCCGCGAGTAA",
                "structure": "(((((((((((.........)))).))))))).........(((((((..((((.((((((..(((((((((((.....))))))))))).......((..(((.(((((((((......((.....))...))))))))).)))..)).....(((((((((.((((((....((((((..((((((..(((((((.....))))..)))....))).)))..)))))).......))))))....((((((((((....(((((((..(((((((((((..((((.....))))))))))))))).....(((((((((.....)))..(((.((((((((...))))))))....)))...))))))...))))).)))))))))))).(((((((..((((((...)).))))...))))))))))))))))...((((((....))))))((((....(((((...............))))).....))))...))).))).))))........(((((.((((...((((((.((((((.((.(((((((........))))....))))).))))))......))))))..(((((((....)))))))..))))))))).(((((((((((....))))).)))))).((((....((((((....)).))))...))))...(((((((((((...(((.(((((.............))))).))).....))).)))......((((((..(((......((((((((((((.((((.....))))(((...((((.((((...((((((((((..((((((((((((..........)))))).)))))).)))))((((((......))))))(((........)))...))))).)))).))))..)))....)))))))).))))..((((((....)))))))))..))))))..))))))))))))......"
            },

            "custom": {}
        }
    ]
}
]
