=== RNABioInfo/rna-interaction-format/examples/sbs.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://raw.githubusercontent.com/Ibvt/rna-interaction-specification/rna-interaction-schema_v1.json",
	"title": "RNA-RNA/Protein Interaction Format",
	"description": "",
	"type": "object",
	"required": ["ID", "class", "type", "evidence"],
	"properties": {
		"ID": {
			"type": "integer",
			"minimum": 0
		},
		"class": {
			"enum": ["RNA-RNA", "RNA-Protein", "RNA-RNA-Protein"]
		},
		"type": {
			"type": "string"
		},
		"evidence": {
			"description": "evidence that supports the interaction",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"type": {
						"description": "type of evidence (e.g., prediction, experimental)",
						"type": "string"
					},
					"method": {
						"description": "Tools or laboratory techniques used",
						"type": "string"
					},
					"command": {
						"description": "",
						"type": "string"
					},
					"data": {
						"type": "object"
					}
				},
				"required": ["type", "method"]
			},
			"minItems": 1,
			"uniqueItems": true
		},
		"partners": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"description": "",
						"type": "string"
					},
					"symbol": {
						"description": "",
						"type": "string"
					},
					"type": {
						"description": "",
						"type": "string"
					},
					"sequence": {
						"description": "",
						"enum": ["dna","rna","protein"]

					},
					"genomic_coordinates": {
						"description": "",
						"type": "string"
					},
					"organism_name": {
						"description": "",
						"type": "string"
					},
					"organism_name": {
						"description": "",
						"type": "string"
					},
					"local_sites": {
						"type": "array"
					},
					"other": {
						"type": "object"
					},
					"custom": {
						"type": "object"
					}
				}
			}
		}

	}
}

=== RNABioInfo/rna-interaction-format/examples/small.json
[{
    "ID": 1,
    "class": "RNA-RNA",
    "type": "basepairing", 
    
    "evidence": [{
            "type": "Direct Duplex Detection", 
            "method": "RANnue", 
            "command": "RNAnue -minfraglen 18 -minlen 36 -sitelenratio 0.3",
            "data": {
                "complementarity": {
                    "unit": "gcs",
                    "value": 0.8
                }
            }
    }],
    "partners": [ 
        {
            "name": "dsrA",
            "symbol": "dsrA", 
            "type": "small_regulatory_ncRNA", 
            "genomic_coordinates": "chr1:+:2025223-2025313",
            "organism_name": "Escherichia coli K-12 MG1655",
            "organism_acc": "NC_000913",
            "local_sites": [ 
                [],[[25,32],[10,17]]
            ]
        },
        {
            "name": "rpoS",
            "symbol": "rpoS",
            "type": "mRNA",
            "genomic_coordinates": "chr1:-:2866559-2867551",
            "organism_name": "Escherichia coli K-12 MG1655",
            "organisms_acc": "NC_000913",
            "local_sites": [ 
                [[70,83],[19,32]],[]
            ]
        }
    ]
}]
